---
#- name: ensure local machine has necessary virt packages
#  yum: name=libguestfs-tools-c state=latest
#  become: true

- name: download base image file
  get_url: url={{ base_image_url }} dest=/tmp/

- name: add 20G empty space to disk image
  shell: qemu-img resize /tmp/{{ base_image_filename }} +20G

- name: create tmp disk for first resize pass
  shell: qemu-img create -f qcow2 -o preallocation=metadata /tmp/osptmp1.qcow2 31G

- name: resize root partition from 6 to 10G
  shell: virt-resize --quiet --resize /dev/sda1=+4G /tmp/{{ base_image_filename }} /tmp/osptmp1.qcow2

- name: create tmp disk for adding second partition for docker thinpool
  shell: qemu-img create -f qcow2 -o preallocation=metadata /tmp/{{ base_image_filename }}_resized_{{ image_tag }}.qcow2 32G

- name: resize second partition to use all free space
  shell: virt-resize --quiet --expand /dev/sda2 /tmp/osptmp1.qcow2 /tmp/{{ base_image_filename }}_resized_{{ image_tag }}.qcow2

- name: set root password in image
  shell: virt-customize --root-password password:{{ root_password }} -a /tmp/{{ base_image_filename }}_resized_{{ image_tag }}.qcow2

- name: inject perf-dept ssh key into image
  shell: virt-customize -a /tmp/{{ base_image_filename }}_resized_{{ image_tag }}.qcow2 --ssh-inject root:string:"ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA57NxnEo8KnrBYRrWjgS8eSZBKiUFBbP4GGbC1M1Kxo+494T2+y3uuihK0Ey5n824ch2OafK7m/TnByIC9pQ3VuAi/ggiOfja2gvZ/GtTedE3ct0jVbGbM/98MS0GV1NoIZRqX6e44JMDqID+ngwQutPyTgxbJ/PL2jVUrjP6sOMEJqgSEbQ9a3s+oM3O0vMTLp7E0PtgKQo0bKRoKFEn5mUxiQ2gmwg/dPqOb2/VpBAKCozsE2illszzyP/KC1gq0VkgMqIZspUsXRqvDDbnaSkCc8/AwA0yBAPBMAjtuk5UZvpioHSh2X0ShcgHtYocZiQIxiSvDzvxdYkFBztu6w== perf-team-shared-key"
