---
- name: install rhel7-cdn repo
  copy: src=rhel7-internal-cdn.repo dest=/etc/yum.repos.d/rhel7-internal-cdn.repo owner=root group=root mode=0644

- name: install EPEL repo
  copy: src=epel.repo dest=/etc/yum.repos.d/

- name: install pbench-internal repo
  template: src=etc/yum.repos.d/pbench.repo.j2 dest=/etc/yum.repos.d/pbench.repo owner=root group=root mode=0644

- name: install pbench-external repo
  copy: src=ndokos-pbench-epel-7.repo dest=/etc/yum.repos.d/

- name: disable requiretty
  replace: dest=/etc/sudoers regexp='^Defaults    requiretty' replace='Defaults    !requiretty' backup=yes
