## JMeter Test Config
## Mention the parameters of each Jmeter Test that are needed to create a Jmeter Test Plan.
## Each test will have its own parameters.
## Each parameter set will correspond to one Jmeter test plan.

## Conditions:
##     1. Test Suite Name has to be unique, otherwise the test plan files will be overwritten.
##     1. Test Suite Name should not contain hyphens (-), used as a seperator for discribing the scenario
##     2. interval between app hits must be mentioned in milliSecs and all other time in Secs
##     3. app URL must be of the format http://<appurl>(optional < :port >)/path_to_resource
##     4. number of users, ramp up time, number of user loops, number of app loops and interval are all arrays.


jmeterTestParameters:
   - testSuiteName: jbosseaproute
     appURL: http://<<jboss app route here >>
     numberOfUsers: [1000]
     rampUpTime: [5]
     numberOfUserLoops: [ 1 ]
     numberOfAppLoops: [100, 200, 500, 700, 1000] 
     intervalBetweenAppHits: [500]
   - testSuiteName: jbosseapdirect
     appURL: http://<<jboss ip here>>:8080
     numberOfUsers: [1000]
     rampUpTime: [5]
     numberOfUserLoops: [ 1 ]
     numberOfAppLoops: [100, 200, 500, 700, 1000] 
     intervalBetweenAppHits: [500]
