- include: ./setup_10g.yml
  vars:
    - interface10g: false
  remote_user: root

- name: Common taks for master and nodes
  hosts: OSEv3
  remote_user: root
  vars:
    - RHEL7_OSE_REPO: http://buildvm-devops.example.com/puddle/build/OpenShiftEnterprise/3.0/latest/RH7-RHOSE-3.0.repo
    - interface10g: false
  roles:
    - ../roles/common

- include: ./setup_dnsmasq.yml
  vars:
    - interface10g: false
  remote_user: root

- include: ./openshift-ansible/playbooks/byo/config.yml
  remote_user: root

- include: ./setup_dnsmasq.yml --tags=post_installation
  vars:
    - interface10g: false
  remote_user: root
 
- name: make the master schduleable, which runs DNSMASQ
  hosts: masters[0]
  remote_user: root
  tasks:
    - name: make the master schduleable
      shell: oadm manage-node {{ hostvars[item].ose3name }} --schedulable=true
      with_items: groups['masters'] 

- include: ./setup_router.yml
  remote_user: root

- include: ./setup_nfs.yml
  hosts: masters

- include: ./setup_registry.yml
  hosts: masters

