---
- name: provision gold images
  user: root
  hosts: all

  roles:
    - clone-repos
    - aos-ansible
    - repo-install
    - os-kickstart
    - collectd-install
    - clone-repos
    - pbench-config
    - docker-config
    - aos-ansible
    - svt-setup
    - openshift-package-install
    - seal-image
